<?php

namespace Cpm\JovenesBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Cpm\JovenesBundle\Filter\CorreoFilter;

/**
 * CorreoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorreoRepository extends EntityRepository
{
	static $sort_criteria = array("id" => "c.id" , "Fecha envio" => "c.fecha");
	
	public function findAllQuery($user_id = null) {
		$qb = $this->getEntityManager()->createQueryBuilder()
		->add('select','c')
		->add('from','CpmJovenesBundle:Correo c')
		->orderBy('c.fecha', 'DESC');
	
		if ($user_id != null)
			$qb->andWhere('c.destinatario = :destinatario')
				->setParameter('destinatario',$user_id);
		
		return  $qb->getQuery();
	}
	
	public function filterQuery(CorreoFilter $filter,$ciclo_activo,$sort_field = null, $sort_order) {
		$qb = $this->createQueryBuilder('c')->orderBy('c.fecha', 'DESC');
		if ($sort_field) {
			$field = (isset(CorreoRepository::$sort_criteria[$sort_field]))?CorreoRepository::$sort_criteria[$sort_field]:CorreoRepository::$sort_criteria['id'];
			$qb->orderBy($field,$sort_order);
		}
		
	/*	$cicloFilter = $filter->getCicloFilter();
		if  ($ciclo = $cicloFilter->getCiclo()) { 
			$qb->innerJoin('c.proyecto', 'p')->andWhere('p.ciclo = :ciclo')->setParameter('ciclo', $ciclo);
		}
		*/
	 	if ($filter->getFecha())
			$qb->andWhere('DATE(c.fecha) = :fecha')->setParameter('fecha',$filter->getFecha());
		if ($filter->getFechaMin())
			$qb->andWhere('c.fecha > :fechaMin')->setParameter('fechaMin',$filter->getFechaMin());
		if ($filter->getFechaMax())
			$qb->andWhere('c.fecha < :fechaMax')->setParameter('fechaMax',$filter->getFechaMax());
		if ($filter->getEmail())
			$qb->andWhere('c.email LIKE :email')->setParameter('email','%'.$filter->getEmail().'%');
	    if ($filter->getAsunto())
			$qb->andWhere('c.asunto LIKE :asunto')->setParameter('asunto',$filter->getAsunto());
	    if ($filter->getCuerpo())
			$qb->andWhere('c.cuerpo LIKE :cuerpo')->setParameter('cuerpo',$filter->getCuerpo());
	    if ($filter->getDestinatario())
			$qb->andWhere('c.destinatario = :destinatario')->setParameter('destinatario',$filter->getDestinatario());
	    if ($filter->getEmisor())
			$qb->andWhere('c.emisor = :emisor')->setParameter('emisor',$filter->getEmisor());
		/*if ($filter->getProyecto())
			$qb->innerJoin('c.proyecto', 'p')->andWhere('p = :proyecto')->setParameter('proyecto',$filter->getProyecto());;
			*/
			//$qb->andWhere('c.proyecto = :proyecto')->setParameter('proyecto',$filter->getProyecto());
		

		return $qb;
	}
	
}