<?php

namespace Cpm\JovenesBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Cpm\JovenesBundle\Filter\DiaFilter;

/**
 * DiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiaRepository extends EntityRepository
{
	public function findAllQuery() {
		$qb = $this->getEntityManager()->createQueryBuilder()
		->add('select','d')
		->add('from','CpmJovenesBundle:Dia d');
	
		return  $qb->getQuery();
	}

	public function filterQuery(DiaFilter $filter,$ciclo_activo,$sort_field = null, $sort_order) {
		
	
	 	$qb = $this->createQueryBuilder('d')
			->addOrderBy('d.numero', 'asc');
		
		$cicloFilter = $filter->getCicloFilter();
		if  ($cicloFilter && ($ciclo = $cicloFilter['ciclo'])) {
			$qb->innerJoin('d.tanda','t')
			->innerJoin('t.instanciaEvento','ie')
			->innerJoin('ie.evento','e')
			->andWhere('e.ciclo = :ciclo')->setParameter('ciclo',$ciclo);
		}
	
		return $qb;
	
	}
}