<?php

namespace Cpm\JovenesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InstanciaEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstanciaEventoRepository extends EntityRepository
{
	public function findAllQuery() {
		$qb = $this->getEntityManager()->createQueryBuilder()
		->add('select','ie')
		->add('from','CpmJovenesBundle:InstanciaEvento ie')
		->add('orderBy','ie.fechaInicio ASC, ie.fechaFin ASC')
		;
	
		return  $qb->getQuery();
	}
}