<?php

namespace Cpm\JovenesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitacionRepository extends EntityRepository
{
	public function findAllQuery() {
		$qb = $this->getEntityManager()->createQueryBuilder()
		->add('select','i')
		->add('from','CpmJovenesBundle:Invitacion i')
		->add('orderBy','i.fechaCreacion ASC')
		;
	
		return  $qb->getQuery();
	}
	
}