<?php

namespace Cpm\JovenesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduccionRepository extends EntityRepository
{
	public function findAllQuery() {
		return $this->createQueryBuilder('p');
	}
	
}