<?php

namespace Cpm\JovenesBundle\Entity;


use Cpm \ JovenesBundle \ Filter \ UsuarioFilter;
use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
	public function findAllQuery($ciclo_activo) {
		$qb = $this->getEntityManager()->createQueryBuilder()
			->add('select','u')
			->add('from','CpmJovenesBundle:Usuario u');
			
		$qb = $this->incluirAdministradores($qb); //se incluyen los administradores
		$qb = $this->incluirCoordinadoresYColaboradores($qb,$ciclo_activo);
		 
    return  $qb->getQuery();
  
	}
	
	public function filterQuery(UsuarioFilter $data, $ciclo_activo,$sort_field = null, $sort_order) {
	//function findBySearchCriteriaQuery($data,$ciclo_activo) {
	
		$qb = $this->getEntityManager()->createQueryBuilder();
	
		$qb->add('select','u')
		->add('from','CpmJovenesBundle:Usuario u');
		
		if ($ciclo = $data->getCiclo()) { 

			if ($data->getSoloCoordinadores()) 
			{  //si solo queria coordinarores, ya estaba el join con proyectos, solo agrego
					$qb->innerJoin('u.proyectosCoordinados','p');
					$qb->innerJoin('p.ciclo','ciclo')->andWhere('ciclo = :ciclo')->setParameter('ciclo',$ciclo);
			
			}
			else 
			{  	
				$qb = $this->incluirCoordinadoresYColaboradores($qb,$ciclo);
			
			}  
		// los administradores no dependen de los ciclos, con lo cual esto ya no tiene sentido
		// $qb = $this->incluirAdministradores($qb); //se incluyen los administradores
					
		} else { 
			if ($data->getSoloCoordinadores()) 
			{  //si solo queria coordinarores, ya estaba el join con proyectos, solo agrego
					$qb->innerJoin('u.proyectosCoordinados','p');
			
			}
		}
		
		if ($data->getApellido()) 
				$qb->andWhere('u.apellido like :apellido')
					->setParameter('apellido',(trim($data->getApellido())."%"));
		if ($data->getEmail()) 
				$qb->andWhere('u.email like :email')
					->setParameter('email',(trim($data->getEmail())."%"));
		
		if ($habilitados = $data->getHabilitados()) {
			if ($habilitados == 1)
				$qb->andWhere('u.enabled = 1');
			else 
				$qb->andWhere('u.enabled <> 1');
		}
		
		if ( $anios = $data->getAniosParticipo() ) {
			foreach ( $anios as $index => $anio ) {
				$var = "anio{$index}"; 
       			$qb->andWhere("u.aniosParticipo like :$var")->setParameter("$var","%$anio%");
			}	
		}
		return $qb;
		
	}
	
	/**
	 * Recibe un QueryBuilder con la entidad Usuario u, y un ciclo $ciclo. 
	 * Retorna el mismo QueryBuilder al cual le agrega dos subqueries para buscar usuarios (u) en proyectos del ciclo $ciclo, ya sean colaboradores o coordinadores de dichos proyectos
	 * 
	 */
	private function incluirCoordinadoresYColaboradores($qb,$ciclo) {
		
			 	$qb_colaboradores = $this->getEntityManager()->createQueryBuilder();
			 	$qb_coordinadores = $this->getEntityManager()->createQueryBuilder();
			 	
			 	$qb_colaboradores->add('select','colaboradores')->add('from','CpmJovenesBundle:Proyecto proyecto')
						 	->innerJoin('proyecto.colaboradores','colaboradores')
						 	->innerJoin('proyecto.ciclo','ciclo')->andWhere('ciclo = :ciclo');
				
				$qb_coordinadores->add('select','coordinadores')->add('from','CpmJovenesBundle:Proyecto proyecto2')
						 	->innerJoin('proyecto2.coordinador','coordinadores')
						 	->innerJoin('proyecto2.ciclo','ciclo2')->andWhere('ciclo2 = :ciclo');
				
			 	$qb->orWhere($qb->expr()->in('u',$qb_coordinadores->getDQL()))->setParameter('ciclo',$ciclo);
			 	$qb->orWhere($qb->expr()->in('u',$qb_colaboradores->getDQL()));
			 	//NOTA: GUARDA CON PONER UN ANDWHERE despues de estos, porque se puede romper el query
			 	
			 	return $qb;
	}
	
	/**
	 * Recibe un QueryBuilder conla entidad Usuario u, y lo amplía para que se incluyan siempre los usuarios administradores
	 */
	private function incluirAdministradores($qb) 
	{ 
		$qb_admin = $this->getEntityManager()->createQueryBuilder();
		$qb_admin->add('select','admins')->add('from','CpmJovenesBundle:Usuario admins')->where('admins.roles like :roleadmin');
		$qb->orWhere($qb->expr()->in('u',$qb_admin->getDQL()))->setParameter('roleadmin','%ROLE_ADMIN%');
		return $qb;	
	}
	
}