security:
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
        Cpm\JovenesBundle\Entity\Usuario: sha1

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/public/
            security: false
        
        secured_area:
            pattern:    ^/
            form_login: 
                login_path: /public/login 
            logout: ~
            
    access_control:
        - { path: ^/public, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
        
    providers:
#       chain_provider:
#            providers: [in_memory, user_db]
       user_db:
            entity: { class: CpmJovenesBundle:Usuario, property: email }
#       in_memory:
#            users:
#                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

