<?php

namespace Cpm\JovenesBundle\Entity;

use Cpm\JovenesBundle\Filter\ArchivoFilter;
use Doctrine\ORM\EntityRepository;

/**
 * ArchivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivoRepository extends EntityRepository
{
	public function findAllQuery() {
		$qb = $this->getEntityManager()->createQueryBuilder()
			->add('select','a')
			->add('from','CpmJovenesBundle:Archivo a')
			->add('orderBy','a.fecha_creado DESC');
		 
    	return  $qb->getQuery();
  
	}
	
	public function filterQuery(ArchivoFilter $filter,$ciclo_activo,$sort_field = null, $sort_order) {
		
		$qb = $this->createQueryBuilder('a')->orderBy('a.fecha_creado', 'DESC');

	 	if ($filter->getNombre())
			$qb->andWhere('a.nombre like :nombre')->setParameter('nombre',"%".$filter->getNombre()."%");
	
		return $qb;
	
		}
		
}