<?php

namespace Cpm\JovenesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CicloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CicloRepository extends EntityRepository
{
	public function getCicloActivo($failFast=true){
		$c = $this->findOneBy(array('activo'=> true));
		if (!$c && $failFast) {
			throw new \IllegalStateException("No hay un ciclo activo");
		}
		
		return $c;
	}
}