<?php

namespace Cpm\JovenesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstadoProyectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoProyectoRepository extends EntityRepository
{
		public function findAllQuery() {
		$qb = $this->getEntityManager()->createQueryBuilder()
		->add('select','ep')
		->add('from','CpmJovenesBundle:EstadoProyecto ep');
	
		return  $qb->getQuery();
	}
	
	
	public function getEstadosAnteriores($proyecto) {
		$qb = $this->getEntityManager()->createQueryBuilder()
					->add('select','e')
					->add('from','CpmJovenesBundle:EstadoProyecto e')
					->andWhere('e.proyecto = :proyecto')->setParameter('proyecto',$proyecto)
					->orderBy('e.fecha','desc')
					->getQuery();
		return $qb->getResult();						
	}
}