<?php

namespace Cpm\JovenesBundle\Entity;
use Cpm \ JovenesBundle \ Filter \ InstanciaEventoFilter;
use Doctrine\ORM\EntityRepository;

/**
 * InstanciaEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstanciaEventoRepository extends EntityRepository
{
	static $sort_criteria = array("id" => "ie.id");
	
	public function findAllQuery($ciclo = null) {
		$qb = $this->createQueryBuilder('ie')
			->innerJoin('ie.evento','e')
			->add('orderBy','ie.fechaInicio ASC, ie.fechaFin ASC')
		;
		if ($ciclo)
			$qb->andWhere('e.ciclo = :ciclo')->setParameter('ciclo',$ciclo);
		
		return  $qb->getQuery();
	}
	
	public function getInstanciasVigentes($ciclo) {
		$qb = $this->createQueryBuilder('ie')
			->add('orderBy','ie.fechaInicio ASC, ie.fechaFin ASC')
		;
		$qb->andWhere('ie.ciclo = :ciclo')->setParameter('ciclo',$ciclo);
		$qb->andWhere('ie.fechaFin < :now')->setParameter('now',new \Datetime());
		
		return  $qb->getQuery()->getResult();
	}
	
	public function filterQuery(InstanciaEventoFilter $data, $ciclo_activo,$sort_field = null, $sort_order) {
		$qb = $this->createQueryBuilder('ie');
										
		 if ($sort_field) {
			$field = (isset(EscuelaRepository::$sort_criteria[$sort_field]))?EscuelaRepository::$sort_criteria[$sort_field]:EscuelaRepository::$sort_criteria['id'];
			$qb->orderBy($field,$sort_order);
		} 

		$qb->innerJoin('ie.evento','e');
		
		$eventoFilter = $data->getEventoFilter();
		if  ($eventoFilter && ($evento = $eventoFilter['evento'])) {
				$qb->andWhere('e = :evento')->setParameter('evento',$evento);
		}
		
		$cicloFilter = $data->getCicloFilter();
		if  ($cicloFilter && ($ciclo = $cicloFilter['ciclo'])) { 
			$qb->andWhere('e.ciclo = :ciclo')->setParameter('ciclo', $ciclo);
		} else {
			$qb->andWhere('e.ciclo = :ciclo')->setParameter('ciclo', $ciclo_activo);
		}
		
		return $qb;
	} 
	
}