<?php

namespace Cpm\JovenesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitacionRepository extends EntityRepository
{
	public function findAllQuery() {
		$qb = $this->getEntityManager()->createQueryBuilder()
		->add('select','i')
		->add('from','CpmJovenesBundle:Invitacion i')
		->add('orderBy','i.fechaCreacion ASC')
		;
	
		return  $qb->getQuery();
	}
	
	
	public function getCantidadesPorInstancia($instancia) {
		
		$qb = $this->getEntityManager()->createQueryBuilder()
		->add('select','i.aceptoInvitacion, count(i.aceptoInvitacion) as cant')
		->add('from','CpmJovenesBundle:Invitacion i')
		->andWhere('i.instanciaEvento = :instancia')->setParameter('instancia',$instancia)
		->add('groupBy','i.aceptoInvitacion')
		;
		$cantidades=array('invitados'=>0, 'confirmaciones'=>0, 'rechazos'=>0);
		$rows = $qb->getQuery()->getResult();
		
		foreach ( $rows as $row ) {
			$cantidades['invitados']+=$row['cant'];
			if ($row['aceptoInvitacion'] == '0'){
				$cantidades['rechazos']=$row['cant'];
			}elseif ($row['aceptoInvitacion'] == '1'){
				$cantidades['confirmaciones']=$row['cant'];
			}
				
		}
		
		return $cantidades;
	}
	
	public function getInvitacionesPendientes($instancia) { 
		$qb = $this->getEntityManager()->createQueryBuilder()
				->add('select','i')
				->add('from','CpmJovenesBundle:Invitacion i')
				->andWhere('i.instanciaEvento = :instancia')->setParameter('instancia',$instancia)
				->andWhere('i.aceptoInvitacion is NULL');
	
			return $qb->getQuery()->iterate();//->getResult(); 
				
	}
	
}