<?php

namespace Cpm\JovenesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
	public function findAllQuery() {
		$qb = $this->getEntityManager()->createQueryBuilder()
			->add('select','u')
			->add('from','CpmJovenesBundle:Usuario u');
		
    	 
    return  $qb->getQuery();
  
	}
	
	function findBySearchCriteriaQuery($data) {
	
		$qb = $this->getEntityManager()->createQueryBuilder();
	
		$qb->add('select','u')
		->add('from','CpmJovenesBundle:Usuario u');
		
		if ($data->getApellido()) $qb->andWhere('u.apellido like :apellido')
									 ->setParameter('apellido',(trim($data->getApellido())."%"));
		if ($data->getEmail()) $qb->andWhere('u.email like :email')
								 ->setParameter('email',(trim($data->getEmail())."%"));
		
		if ($habilitados = $data->getHabilitados()) {
			if ($habilitados == 1)
				$qb->andWhere('u.enabled = 1');
			else $qb->andWhere('u.enabled <> 1');
		}
		
		if ($data->getCoordinadores()) $qb->innerJoin('u.proyectosCoordinados','p');
		
		if ($ciclo = $data->getCiclo()) {
			if ($data->getCoordinadores()) 
			{  //si solo queria coordinarores, ya estaba el join con proyectos, solo agrego
				$qb->innerJoin('p.ciclo','ciclo')->andWhere('ciclo = :ciclo')->setParameter('ciclo',$ciclo);
			}
			else 
			{ //si quiere coordinadores y colaboradores, tengo que hacer leftJoins
			 	
			 	$qb_colaboradores = $this->getEntityManager()->createQueryBuilder();
			 	$qb_coordinadores = $this->getEntityManager()->createQueryBuilder();
			 	
			 	$qb_colaboradores->add('select','colaboradores')->add('from','CpmJovenesBundle:Proyecto proyecto')
						 	->innerJoin('proyecto.colaboradores','colaboradores')
						 	->innerJoin('proyecto.ciclo','ciclo')->andWhere('ciclo = :ciclo');
				
				$qb_coordinadores->add('select','coordinadores')->add('from','CpmJovenesBundle:Proyecto proyecto2')
						 	->innerJoin('proyecto2.coordinador','coordinadores')
						 	->innerJoin('proyecto2.ciclo','ciclo2')->andWhere('ciclo2 = :ciclo');
				
			 	
			 	$qb->orWhere($qb->expr()->in('u',$qb_coordinadores->getDQL()))->setParameter('ciclo',$ciclo);
			 	$qb->orWhere($qb->expr()->in('u',$qb_colaboradores->getDQL()));
			 	//NOTA: GUARDA CON PONER UN ANDWHERE despues de estos, porque se puede romper el query
			}  
			
		} 
		return $qb->getQuery();
		
	}
	
}